global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - alert.rules

scrape_configs:
  - job_name: prometheus
    consul_sd_configs:
    - server: localhost:8500
      services:
        - internal-prometheus
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
  - job_name: federate
    honor_labels: true
    metrics_path: '/federate'
    consul_sd_configs:
    - server: localhost:8500
      services:
        - internal-prometheus
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
    params:
      'match[]':
        - '{__name__=~".+"}'
    